export const FETCH_CREATE_TOKENS_PAIR = "FETCH_CREATE_TOKENS_PAIR";
export const FETCH_UPDATE_ACCESS_TOKEN = "FETCH_UPDATE_ACCESS_TOKEN";
export const FETCH_VERIFY_ACCESS_TOKEN = "FETCH_VERIFY_ACCESS_TOKEN";

export const SET_IS_LOGIN = "SET_IS_LOGIN";
export const IS_LOGIN_REQUEST_LOADING = "IS_LOGIN_REQUEST_LOADING";
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";
