export const FETCH_GET_USERS_LIST = "FETCH_GET_USERS_LIST";
export const SET_USERS_LIST = "SET_USERS_LIST";
export const SET_USERS_LIST_IS_LOADING = "SET_USERS_LIST_IS_LOADING";
export const SET_MODAL_IS_VISIBLE = "SET_MODAL_IS_VISIBLE";
