export const FETCH_GET_TASKS_LIST = "FETCH_GET_TASKS_LIST";
export const SET_IS_TASKS_LIST_LOADING = "SET_IS_TASKS_LIST_LOADING";
export const SET_TASKS_LIST = "SET_TASKS_LIST";
export const SET_AUTOCOMPLETE_TASKS_LIST = "SET_AUTOCOMPLETE_TASKS_LIST";
export const FETCH_GET_TASKS_AUTOCOMPLETE = "FETCH_GET_TASKS_AUTOCOMPLETE";
